### ISSUE TITLE
Migrate to react-navigation 5.0 

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/croma-react#100]
https://reactnavigation.org/docs/4.x/upgrading-from-3.x/
https://reactnavigation.org/docs/upgrading-from-4.x/

**Comment by EduardoFLima** [comment]
I would like to work on this issue

**Comment by kamalkishor1991** [comment]
Thanks, Assigned.

**Comment by kamalkishor1991** [comment]
the version is now ~ 6.0.0
