### ISSUE TITLE
Change billing library to react-native-iap

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/croma-react#125]
The current one is not maintained and google is expiring it support in few months.
https://github.com/dooboolab/react-native-iap

**Comment by hardiktulsiani1110** [comment]
Hi, can I work on this issue?

**Comment by kamalkishor1991** [comment]
sure @hardiktulsiani1110. Please let me know if you need any help.

**Comment by kamalkishor1991** [comment]
This feature is implemented and released in bith ios and android.
