### ISSUE TITLE
Header content and icons  not showing in safari browser 

### ISSUE THREAD

**Issue by bhujoshi** [croma-app/croma-react#65]
Open https://croma.app on the safari browser. You will notice  header content and icons are not showing in the safari browser 

**On Safari** 
![Screen Shot 2020-04-28 at 12 29 33 PM](https://user-images.githubusercontent.com/9627563/80458478-7c0e7c80-894e-11ea-9458-4a1c3e6a98d3.png)

**On Chrome**
![Screen Shot 2020-10-05 at 8 34 35 PM](https://user-images.githubusercontent.com/9627563/95096736-4a45e100-074a-11eb-965a-1100af896bc2.png)

**Comment by ashokaditya** [comment]
Hi @bhujoshi I'd like to take a look at this.

**Comment by ashokaditya** [comment]
👍

**Comment by bhujoshi** [comment]
Thanks, @ashokaditya Let me know in case you need any help.

**Comment by ashokaditya** [comment]
I should have a PR ready today sometime 😄
